# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

env:
  es6: true
  mocha: true
  node: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - '@typescript-eslint'
