name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1.0.2
      - name: Run MSBuild
        run: msbuild
      - name: PowerShell Tests
        shell: pwsh
        run: .\PipelinesTasks\PRMetrics\Tools\Validate.ps1
      - name: PowerShell Analyzer
        uses: devblackops/github-action-psscriptanalyzer@v2.3.0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
