# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: null

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [PRMetrics]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install Root NPM Dependencies
        run: npm install

      - name: Install NPM Dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Build
        run: npm run build
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Test
        run: npm test
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Remove 'node_modules'
        run: Remove-Item -Path 'node_modules' -Recurse -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Install Production NPM Dependencies
        run: npm install --only=production
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Remove '.nyc_output'
        run: Remove-Item -Path '.nyc_output' -Recurse -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Remove '.taskkey'
        run: Remove-Item -Path '.taskkey' -Recurse -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Remove 'tests'
        run: Remove-Item -Path 'tests' -Recurse
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Remove 'tsdocs'
        run: Remove-Item -Path 'tsdocs' -Recurse -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Remove '*.js.map'
        run: Get-ChildItem -Path '*' -Include '*.js.map' -Recurse | Remove-Item -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Remove '*.json'
        run: Remove-Item -Path '*.json' -Exclude 'task*.json' -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Remove '*.ts'
        run: Get-ChildItem -Path '*' -Include '*.ts' -Recurse | Remove-Item -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask

      - name: Copy to Destination
        run: Copy-Item -Path '${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}' -Destination '${{ github.workspace }}/build/Release/PipelinesTasks/${{ matrix.task }}' -Recurse

      - name: Copy 'LICENSE.txt'
        run: Copy-Item -Path '${{ github.workspace }}/LICENSE.txt' -Destination '${{ github.workspace }}/build/Release/PipelinesTasks/${{ matrix.task }}'

      - name: Install TFX CLI
        run: npm install -g tfx-cli

      - name: Create Release
        run: tfx extension create --manifest-globs vss-extension.json --output-path ms-omex.${{ matrix.task }}.vsix
        working-directory: ${{ github.workspace }}/build/Release/PipelinesTasks/${{ matrix.task }}

      - name: Upload VSIX
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.task }}
          path: '**/*.vsix'

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Super Linter
        uses: github/super-linter@v3.15.5
        env:
          EDITORCONFIG_FILE_NAME: ../../.editorconfig
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_CONFIG_FILE: ../../.markdownlint.json
          TYPESCRIPT_ES_CONFIG_FILE: ../../.eslintrc.yml
          VALIDATE_POWERSHELL: false # TODO: Enable when PowerShell is deleted

      - name: Validate Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/linters/markdown-link-check.json

      - name: Validate .markdownlint.json
        uses: Zingabopp/JsonValidate-Action@v1
        with:
          json-file: .markdownlint.json
          json-schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json
          use-draft: draft-07

      - name: Security Scan – Validate
        uses: ShiftLeftSecurity/scan-action@v1.3.0
        with:
          type: credscan,depscan

      - name: Security Scan – Upload Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports

  validate-task:
    name: Validate – Task
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [PRMetrics]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download tasks.schema.json
        run: Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/microsoft/azure-pipelines-task-lib/master/tasks.schema.json' -OutFile 'tasks.schema.json'

      - name: Update tasks.schema.json
        run: |-
          $FileContent = Get-Content -Path 'tasks.schema.json' -Raw
          $FileContent = $FileContent -replace 'draft-04', 'draft-07'
          Set-Content -NoNewline -Path 'tasks.schema.json' -Value $FileContent

      - name: Validate task.json
        uses: Zingabopp/JsonValidate-Action@v1
        with:
          json-file: PipelinesTasks/${{ matrix.task }}/buildAndReleaseTask/task.json
          json-schema: tasks.schema.json
          use-draft: draft-07
