name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: MSBuild – Install
        uses: microsoft/setup-msbuild@v1.0.2
      - name: MSBuild – Run
        run: msbuild
      - name: PowerShell Tests – Install
        shell: pwsh
        run: Install-Module -Name 'Pester' -Force
      - name: PowerShell Tests – Run
        shell: pwsh
        run: |
          $Result = Invoke-Pester
          $Result
          if ($Result -notlike '*Failed: 0,*') { Throw 'PowerShell Tests failed.' }
      # - name: PowerShell Tests – Run
      #   id: powershell_tests
      #   uses: zyborg/pester-tests-report@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: PowerShell Tests – Results
      #   shell: pwsh
      #   run: |
      #     Write-Information -MessageData 'Test:   ${{ steps.powershell_tests.outputs.total_count }}' -InformationAction Continue
      #     Write-Information -MessageData 'Passed: ${{ steps.powershell_tests.outputs.passed_count }}' -InformationAction Continue
      #     Write-Information -MessageData 'Failed: ${{ steps.powershell_tests.outputs.failed_count }}' -InformationAction Continue

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PowerShell Analysis – Install
        shell: pwsh
        run: Install-Module -Name 'PSScriptAnalyzer' -Force
      - name: PowerShell Analysis – Run
        shell: pwsh
        run: |
          $Result = (Invoke-ScriptAnalyzer -Path '.' -Recurse | Where-Object -Property 'RuleName' -ne 'TypeNotFound')
          $Result
          if ($Result.Count -gt 0) { Throw 'PowerShell Analysis failed.' }
