# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Deploy

on:
  workflow_dispatch: null

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [PRMetrics]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Build
        run: npm run build:release
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/task

      - name: Remove 'task'
        run: Remove-Item -Path 'task' -Force -Recurse
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}

      - name: Copy 'LICENSE.txt'
        run: Copy-Item -Path '${{ github.workspace }}/LICENSE.txt' -Destination '${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}'

      - name: Login
        run: tfx login --service-url https://${{ secrets.AZURE_DEVOPS_INSTANCE }}.visualstudio.com/DefaultCollection --token ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }} --no-prompt
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/task

      - name: Deploy
        run: npm run deploy
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/task
