# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Deploy

on:
  workflow_dispatch: null

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [PRMetrics]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Build
        run: npm run build:release
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/task

      - name: Remove 'task'
        run: Remove-Item -Path 'task' -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}

      - name: Copy 'LICENSE.txt'
        run: Copy-Item -Path '${{ github.workspace }}/LICENSE.txt' -Destination '${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}'

      - name: Install TFX CLI
        run: npm install -g tfx-cli

      - name: TFX - Login
        run: tfx login --service-url https://${{ secrets.AZURE_DEVOPS_INSTANCE }}.visualstudio.com/DefaultCollection --token ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }} --no-prompt

      - name: TFX - Delete Old Task
        env:
          taskId: >-
            {
              "PRMetrics": "907d3b28-6b37-4ac7-ac75-9631ee53e512"
            }
        run: tfx build tasks delete --task-id ${{ fromJson(env.taskId)[matrix.task] }} --no-prompt
        continue-on-error: true

      - name: TFX - Upload New Task
        run: tfx build tasks upload --task-path ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/build/release --no-prompt
