name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: MSBuild – Install
        uses: microsoft/setup-msbuild@v1.0.2
      - name: MSBuild – Run
        run: msbuild
      - name: Install TFX CLI
        shell: pwsh
        run: npm install -g tfx-cli
      - name: Create PRMetrics Package
        shell: pwsh
        run: |
          cd ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics
          tfx extension create --manifest-globs vss-extension.json
      - name: Publish PRMetrics to Marketplace
        uses: mrluje/vs-marketplace-publisher@v2
        with:
          pat: ${{ secrets.VS_PAT }}
          manifestPath: ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics\vss-extension.json
