name: Release

on:
  workflow_dispatch:
  release:
    types:
    - created

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: MSBuild – Install
        uses: microsoft/setup-msbuild@v1.0.3
      - name: MSBuild – Run
        run: msbuild
      - name: Install TFX CLI
        shell: pwsh
        run: npm install -g tfx-cli
      - name: PRMetrics Package – Create
        shell: pwsh
        run: |
          cd ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics
          tfx extension create --manifest-globs vss-extension.json
      - name: PRMetrics Package – Publish
        shell: pwsh
        run: >-
          tfx extension publish
          --manifest-globs ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics\vss-extension.json
          --vsix ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics\ms-omex.prmetrics-1.0.3.vsix
          --token ${{ secrets.VS_PAT }}
