# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Release

on:
  release:
    types:
      - created
  workflow_dispatch: null

defaults:
  run:
    shell: pwsh

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [PRMetrics]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: NPM – Install Dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/src/task

      - name: NPM – Release
        run: npm run release
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/src/task

      - name: Publish Release
        run: >-
          tfx extension publish
          --manifest-globs ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/src/task/vss-extension.json
          --vsix ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/src/task/ms-omex.${{ matrix.task }}.vsix
          --token ${{ secrets.VS_PAT }}
