name: Release

on:
  workflow_dispatch:
  release:
    types:
    - created

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag – Get Latest
        uses: oprypin/find-latest-tag@v1.0.4
        id: latest-tag
        with:
          repository: microsoft/OMEX-Azure-DevOps-Extensions
          releases-only: true
      - name: Tag – Remove Prefix
        uses: bhowell2/github-substring-action@v1.0.0
        id: latest-tag-prefix
        with:
          value: ${{ steps.latest-tag.outputs.tag }}
          index_of_str: "v"
      - name: Tag – Extract
        uses: rishabhgupta/split-by@v1.0.1
        id: latest-tag-split
        with:
          string: ${{ steps.latest-tag-prefix.outputs.substring }}
          split-by: '.'
      - name: Tag – Replace Version 1
        uses: datamonsters/replace-action@v2
        with:
          files: "PipelinesTasks/PRMetrics/vss-extension.json,PipelinesTasks/PRMetrics/task/task.json"
          replacements: "%MAJOR%=${{ steps.latest-tag-split.outputs._0 }},%MINOR%=${{ steps.latest-tag-split.outputs._1 }},%PATCH%=${{ steps.latest-tag-split.outputs._2 }}"
      - name: Tag – Replace Version 2
        uses: datamonsters/replace-action@v2
        with:
          files: "PipelinesTasks/PRMetrics/vss-extension.json,PipelinesTasks/PRMetrics/task/task.json"
          replacements: "%MAJOR%=${{ steps.latest-tag-split.outputs._0 }},%MINOR%=${{ steps.latest-tag-split.outputs._1 }},%PATCH%=${{ steps.latest-tag-split.outputs._2 }}"
      - name: MSBuild – Install
        uses: microsoft/setup-msbuild@v1.0.2
      - name: MSBuild – Run
        run: msbuild
      - name: Install TFX CLI
        shell: pwsh
        run: npm install -g tfx-cli
      - name: PRMetrics Package – Create
        shell: pwsh
        run: |
          cd ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics
          tfx extension create --manifest-globs vss-extension.json --output-path ms-omex.prmetrics.vsix
      - name: PRMetrics Package – Validate
        shell: pwsh
        run: >-
          tfx extension isvalid
          --vsix ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics\ms-omex.prmetrics.vsix
          --token ${{ secrets.VS_PAT }}
      # - name: PRMetrics Package – Publish
        # shell: pwsh
        # run: >-
        #   tfx extension publish
        #   --bypass-validation
        #   --manifest-globs ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics\vss-extension.json
        #   --vsix ${{ github.workspace }}\Release\PipelinesTasks\PRMetrics\ms-omex.prmetrics.vsix
        #   --token ${{ secrets.VS_PAT }}
