# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Release

on:
  release:
    types:
      - created
  workflow_dispatch: null

defaults:
  run:
    shell: pwsh

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [PRMetrics]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install Root NPM Dependencies
        run: npm install

      - name: Install NPM Dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask

      - name: Build
        run: |-
          Set-Location -Path '${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask'
          npm run build

      - name: Remove 'node_modules'
        run: Remove-Item -Path 'node_modules' -Recurse -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask

      - name: Install Production NPM Dependencies
        run: npm install --only=production
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask

      - name: Remove 'tests'
        run: Remove-Item -Path 'tests' -Recurse
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask

      - name: Remove 'tsdocs'
        run: Remove-Item -Path 'tsdocs' -Recurse -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask

      - name: Remove '*.js.map'
        run: Get-ChildItem -Path '*' -Include '*.js.map' -Recurse | Remove-Item -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask

      - name: Remove '*.json'
        run: Remove-Item -Path '*.json' -Exclude 'task*.json' -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask

      - name: Remove '*.ts'
        run: Get-ChildItem -Path '*' -Include '*.ts' -Recurse | Remove-Item -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/buildTask

      - name: Copy to Destination
        run: Copy-Item -Path '${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}' -Destination '${{ github.workspace }}/build/Release/PipelinesTasks/${{ matrix.task }}' -Recurse

      - name: Copy 'LICENSE.txt'
        run: Copy-Item -Path '${{ github.workspace }}/LICENSE.txt' -Destination '${{ github.workspace }}/build/Release/PipelinesTasks/${{ matrix.task }}'

      - name: Install TFX CLI
        run: npm install -g tfx-cli

      - name: Create Release
        run: tfx extension create --manifest-globs vss-extension.json --output-path ms-omex.${{ matrix.task }}.vsix
        working-directory: ${{ github.workspace }}/build/Release/PipelinesTasks/${{ matrix.task }}

      - name: Publish Release
        run: >-
          tfx extension publish
          --manifest-globs ${{ github.workspace }}/build/Release/PipelinesTasks/${{ matrix.task }}/vss-extension.json
          --vsix ${{ github.workspace }}/build/Release/PipelinesTasks/${{ matrix.task }}/ms-omex.${{ matrix.task }}.vsix
          --token ${{ secrets.VS_PAT }}
