# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Release

on:
  release:
    types:
      - created
  workflow_dispatch: null

defaults:
  run:
    shell: pwsh

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [PRMetrics]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install Root NPM Dependencies
        run: npm install

      - name: Install NPM Dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/task

      - name: Build
        run: npm run build:release
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/task

      - name: Remove 'task'
        run: Remove-Item -Path 'task' -Force
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}

      - name: Copy 'LICENSE.txt'
        run: Copy-Item -Path '${{ github.workspace }}/LICENSE.txt' -Destination '${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}'

      - name: Install TFX CLI
        run: npm install -g tfx-cli

      - name: Create Release
        run: tfx extension create --manifest-globs vss-extension.json --output-path ms-omex.${{ matrix.task }}.vsix
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}

      - name: Publish Release
        run: >-
          tfx extension publish
          --manifest-globs ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/vss-extension.json
          --vsix ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/ms-omex.${{ matrix.task }}.vsix
          --token ${{ secrets.VS_PAT }}
